# Generated by Django 3.0 on 2020-09-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20200902_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
