# Generated by Django 3.0.8 on 2020-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200730_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feild',
            field=models.BooleanField(default=False),
        ),
    ]
