# Generated by Django 3.0.8 on 2020-08-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200808_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.TextField(),
        ),
    ]
