# Generated by Django 3.0.8 on 2020-08-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200808_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNamePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='World',
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
