# Generated by Django 3.0 on 2020-09-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
        migrations.AddField(
            model_name='movies',
            name='imagename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
