# Generated by Django 3.0 on 2020-09-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200915_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='moviecontext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
