# Generated by Django 3.0 on 2020-09-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200917_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='hallname',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='locationname',
        ),
    ]
