# Generated by Django 3.0 on 2020-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200917_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='hallname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='locationname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
